// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rykbyzediigwcstuzvnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5a2J5emVkaWlnd2NzdHV6dm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4OTk1NDQsImV4cCI6MjA4NjQ3NTU0NH0.kfnxkxVc9mSoVUnu9EhqB1-2iOjnKHashT9J5PLbFjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});